### ISSUE TITLE
Translation from German?

### ISSUE THREAD

**Issue by ChrisClems** [FriendsOfCADability/CADability#190]
There is a mix of German and English commenting. It seems the newer code is commented in English while code from the original commit is commented in German.

Is the intent to have English commenting moving forward? If I were to translate some of the older comments into English as I come across them, would you like the German comments preserved as well or replaced?

**Comment by dsn27** [comment]
I would appreciate it if we could switch to English. That would allow a broader community to participate.
The German comments can be removed.
